/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Admin: typeof import('./src/components/layouts/admin.vue')['default']
    Captcha: typeof import('./src/components/captcha/index.vue')['default']
    Control: typeof import('./src/components/layouts/control.vue')['default']
    Copyright: typeof import('./src/components/layouts/item/copyright.vue')['default']
    Countdown: typeof import('./src/components/countdown/index.vue')['default']
    DragView: typeof import('./src/components/drag-view/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ItemFooter: typeof import('./src/components/layouts/item/item-footer.vue')['default']
    ItemHeader: typeof import('./src/components/layouts/item/item-header.vue')['default']
    ItemLogo: typeof import('./src/components/layouts/item/item-logo.vue')['default']
    ItemMenuItem: typeof import('./src/components/layouts/item/item-menu-item.vue')['default']
    MarkedEditor: typeof import('./src/components/marked-editor/index.vue')['default']
    MarkedText: typeof import('./src/components/marked-text/index.vue')['default']
    Permissions: typeof import('./src/components/permissions/index.vue')['default']
    Qrcode: typeof import('./src/components/qrcode/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Uploads: typeof import('./src/components/uploads/index.vue')['default']
    XlBundle: typeof import('./src/components/form-builder/xl-bundle/index.vue')['default']
    XlChildren: typeof import('./src/components/form-builder/xl-children/index.vue')['default']
    XlPrompt: typeof import('./src/components/form-builder/xl-prompt/index.vue')['default']
    XlTableColumnForm: typeof import('./src/components/form-builder/xl-table-column-form/index.vue')['default']
    XlTableTimes: typeof import('./src/components/form-builder/xl-table-times/index.vue')['default']
    XlTableUserinfo: typeof import('./src/components/form-builder/xl-table-userinfo/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
